#!/bin/sh

# exit if any command fails
# set -eo pipefail ...why does that not work?
set -e

# run script from drupal root
# syntax:
# `dinstall profilename single`
# or
# `dinstall profilename multi sitename`
# display message if no arguments supplied:
if [ $# -eq 0 ]; then
  printf "Install Drupal site\nRun command from Drupal root\nSpecify name of *install profile* then *single/multi* and if multi then *sitename*:\n dinstall standard single\n dinstall standard multi sitename\n"
  exit 64
fi


if [ $2 = 'single' ]; then
  name="$(echo $PWD | sed 's/\/var\/www\///' | sed 's/\/docroot//')"
  sudo chmod -R 775 .
  sudo chown -R alec:www-data .
  drush si $1 --db-url=mysql://root:lOv131@localhost/$name --site-name=$name -y
  cp /etc/apache2/sites-available/blank.conf /etc/apache2/sites-available/$name.dev.conf
  sed -i "s@PWD@$PWD@" /etc/apache2/sites-available/$name.dev.conf
  sed -i "s/NAME/$name/" /etc/apache2/sites-available/$name.dev.conf
  sudo a2ensite $name.dev
  sudo service apache2 restart
  echo '127.0.0.1 newsitename.dev' >> /etc/hosts
  sudo sed -i "s/newsitename/$name/" /etc/hosts
  # now it should move db config from settings.php to local.settings.php
  # wouldn't that be cool :)
fi

if [ $2 = 'multi' ]; then
  name="$3"
  rootdir="$(echo $PWD | sed 's/\/var\/www\///')"
  sudo chmod -R 775 .
  sudo chown -R alec:www-data .
  drush8 si $1 --db-url=mysql://root:lOv131@localhost/$name --site-name=$name --sites-subdir=$name -y
  cp /etc/apache2/sites-available/blank.conf /etc/apache2/sites-available/$name.dev.conf
  sed -i "s@PWD@$PWD@" /etc/apache2/sites-available/$name.dev.conf
  sed -i "s/NAME/$name/" /etc/apache2/sites-available/$name.dev.conf
  sudo a2ensite $name.dev
  sudo service apache2 restart
  echo '127.0.0.1 newsitename.dev' >> /etc/hosts
  sudo sed -i "s/newsitename/$name/" /etc/hosts
  sed -i "/);/i \t'$name.dev' => '$name'," sites/sites.php
fi
