#!/bin/bash

git init
echo "*~" > .gitignore
echo "*.swp" >> .gitignore
echo "*.swo" >> .gitignore
echo "*.tmp" >> .gitignore
echo "*.sql" >> .gitignore
echo "*.zip" >> .gitignore
echo "*.tgz" >> .gitignore
echo "*.tar.gz" >> .gitignore
git add .gitignore
git commit -m "Begin."
