#!/bin/bash
# list *all* files, since `ls` doesn't provide a flag/option for this

if [ $# -eq 0 ]; then
  find -maxdepth 1 -type f | sed 's/\.\///g' | sort
else
  find $1 -maxdepth 1 -type f | sort
fi
